/* Generated By:JavaCC: Do not edit this line. parser_logoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parser_logoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int fonction = 9;
  /** RegularExpression Id. */
  int nbr = 10;
  /** RegularExpression Id. */
  int couleur = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<fonction>",
    "<nbr>",
    "<couleur>",
    "\"POUR\"",
    "\"FIN\"",
    "\"REPETE\"",
    "\"FINREPETE\"",
    "\"AVANCE\"",
    "\"RECULE\"",
    "\"TOURNEDROITE\"",
    "\"TOURNEGAUCHE\"",
    "\"LEVECRAYON\"",
    "\"BAISSECRAYON\"",
    "\"TAILLECRAYON\"",
    "\"COULEUR\"",
    "\"EFFACE\"",
    "\"(\"",
    "\")\"",
  };

}
